# Teaching Statement

#### Teaching Philosophy {-}
  I believe that the best way to learn math is through making mistakes, getting confused, and struggling toward a solution. I consider myself a coach and a facilitator and teach with the core philosophy that my primary goal is to provide my students with a welcoming and inclusive environment where experimentation is encouraged and honest mistakes aren't penalized. 
  I use active learning techniques in all my classes. 
  I believe that a math classroom is a place for students, and even the instructor, to grow as mathematicians.

  My teaching experience ranges from creating advanced electives and short bootcamp courses for small groups of students, to managing and teaching in-person courses with several hundred students, coordinating multi-section classes, and adapting large service courses for asynchronous education. I have contributed to open source texts using technologies such as Webwork, Pretext, and RMarkdown and I'm involved in the long-term project of math-formalization using the Lean theorem prover. I have taught topics spanning calculus, linear algebra, differential equations, discrete math, linear programming, proof checking using computers, manifolds, and algebraic topology.


#### Use of Technology {-}
  Students retain their knowledge better when they engage with a subject through multiple modalities. I find technological tools to be perfect for accomplishing this. I created weekly Excel worksheets for modeling linear programming scenarios. For Discrete Math, I used an online textbook which had (compulsory) interactive activities scattered throughout the text and made YouTube videos for each section which were embedded directly in the textbook. 
  Student responses for these have been overwhelming positive.

  I strongly believe in making education more accessible by creating open educational resources (OER). We now have the technological tools to make this possible. 
  I have co-received an OER Faculty Grant for adding WeBWorK exercises to my colleagues's Linear Algebra OER textbook written in PreTeXt. I also intend to turn my Optimization course notes into an OER textbook. I already make all my course notes available on my personal website.  

#### Diversifying Assessments {-}
  Students often perform poorly on exams not because of a lack of understanding but because of exam anxiety and lack of exam-taking skills. 
  Traditional exams do not faithfully represent the challenges students are likely to face in real life either.
  As such, in every course I teach I try to provide a variety of assessments catered specifically to students' needs. In my Optimization course, students had to submit an Excel Workbook involving several modeling exercises instead of taking a final exam. For Discrete Math, which was taught during Covid, we created a repository of new WeBWorK problems over the summer and replaced in-person exams with ones on WeBWorK and Zoom. Students also had to submit weekly short auto-graded assignments within the textbook which provided immediate feedback. For Algebraic Topology course, I replaced the final exam with an oral exam and a written report as I was more interested in testing students' ability to approach a challenging problem than actually getting a rigorous proof in a short amount of time.
  
#### Course Design {-}
  I continually update my courses as every cohort of students is unique. 
  I try to imagine the course from students' perspective and adapt it to their level of mathematical maturity while being vigilant of the expert blind spot.
  It is very important for me that my course is meaningful and intellectually fulfilling to students.
  I completely restructured my Optimization course to make applications and modeling an essential component. 
  I wrote my own set of notes using RMarkdown as I did not find books with the right mix of theory and applications. 
  I have designed and taught a fully flipped Honors Single Variable Calculus course at JHU. 
  At Canada/USA Mathcamp, I had to develop and teach a short five-day class every week for five weeks while being involved with other camp activities;
  I could not have asked for better training grounds for course design.  


#### Classroom Environment {-}
  I make great efforts to ensure that a course syllabus is welcoming and encouraging, being the first document that students see. 
  While teaching online during Covid, my priority was to alleviate student anxiety and ensuring that students were not disadvantaged because of lack of face-to-face meetings and technical difficulties. 
  After each (autograded) exam, I went through all student responses to reassign any points lost due to minor typos and system errors.
  I also maintained an active discussion forum on Piazza to foster a sense of community.
  I have taught huge coordinated courses where I was the sole point of contact for over 150 students.
  This challenging experience taught me how to be more inclusive and considerate of students from very diverse backgrounds and to ensure that even those who had other priorities could benefit from learning math in whatever way possible.

  I strive to get my students comfortable with the messy process of discovery in math.
  My classes are fun, interactive, and often times flipped.
  I greatly value one-to-one interactions as these allow students to get to know me as an individual.
  It is important for me and valuable for students to see me struggle and make mistakes. 
  I hold a lot of office hours in a collaborative space that encourages group work.
  My office hours always have a high attendance.
  I memorize all of my students' names so that I can connect with them on a personal level.

#### Professional Development {-}
  I try to keep myself updated on the advances in pedagogical techniques and find it valuable to hear about other educators' teaching experiences.
  I am a member of the Project NExT'20 cohort, a professional development program sponsored by the MAA for math educators at the university level.
  I have completed a certification course at the Teaching Academy at JHU where I learned about several important pedagogical concepts such as inquiry-based learning, backward course design, learning objectives, etc. which I regularly incorporate into my own teaching.
  I regularly attend the workshops and seminars organized at the Center for Teaching and Learning at both UWO and NU and most recently Open Math Workshops and SIGMAA IBL workshops by MAA.
  In addition to providing me new information and skills, these workshops also allow me to take on the role of a student and stay grounded.

#### Mentorship {-}
  I find it fulfilling to mentor students outside of the regular classroom setting. 
  I am currently a supplementary instructor for the Causeway Postbaccalaureate Program, a yearlong experience in mathematics that seeks to increase the number of graduate students in the mathematical sciences from historically underrepresented groups. 
  I am also a co-organizer of the Northwestern Emerging Scholars Program, which is similar to math circles for first-year students.  
  I have organized and participated in a Directed Reading Program that pairs undergraduate students with graduate students/junior faculty to undertake independent study projects as a mentor and a co-organizer. 
  I started a DRP chapter at UWO here with the help of one of my colleagues. 

  My biggest influences have come from being a mentor (2017-20) and an academic coordinator
  (2018) at the Canada/USA Mathcamp, a summer program for high school students.
  Mathcamp gave me an opportunity to be a part of a loving and caring community, to be surrounded by people who love math and love to teach it and excel at it.
  I took on the role of an academic coordinator to contribute back to Mathcamp, to challenge myself, and to learn more about teaching. 
  The academic coordinators are responsible for designing and running all the academic activities, including, inviting and hosting external visitors, designing a balanced five-week class schedule (nearly 60 classes), assigning (110) students to projects, and teaching. 

#### Future Goals {-}
  My next big goal is to figure out ways to quantitatively assess my teaching and pedagogical effectiveness.
  I wish to teach more interdisciplinary courses that involve student projects and real world applications.
  In the winter quarter, I intend to use SIMIODE textbook, which takes a modeling first approach, for teaching differential equations.
  I am currently contributing to Open Education Resources and wish to expand these projects in the future with focus on book publishing and online assessments as these resources are bound to play a central role in successfully adapting courses to an online setting.

#### Selected Student Feedback {-}

- This[Optimization] was the best math class I've taken so far at Northwestern. For the first time, I feel like I will carry the material I learned in class
for years and years, as it's so applicative to real world problems. 
- Optimization is a really useful and practical math course that all math majors should take. It isn't very proof-heavy and focuses
more on computation.    
- Apurva is phenomenal! He broke down key concepts with ease, and homework questions went over a variety of different examples.
Optimization is interesting as a whole due to it wide applicability in other fields, but I felt this was an enjoyable course because of
Apurva
- Dr. Nakade is the best teacher for second-year software engineering. Your recorded lectures are very clear and make me happy as I
actually understand after watching them. You seem like a very hard-working professor that truly cares about their students. Thank you!
The zybook and PA and CA are just perfect for making me on-track. I'm never behind in this class because of the PA and CA.
- The PAs and CAs are helpful and
fun and an interactive way that helps me learn the concepts better. I like that I am not punished for when I get an answer incorrect and
am instead presented with the solution so I can better understand it while learning. The webworks assessments are also a good and
fair evaluation of my understanding 
(Also, thank you for not using Proctortrack because the idea of it really stresses me out.)
- The use of ZyBooks to teach discrete math was an absolute genius move, as the online textbook paired with the instructor videos were
extremely clear in explaining and testing knowledge of mathematical concepts. I recommend using it for future years
- Apurva is the best Professor. Though his lecture notes can have minor mistakes, he is a very nice guy and you can ask him
questions without being intimidated. His office hours are very helpful and talking to him about non–math things are also a lot of fun.
- Professor Nakade is so kind and enthusiastic about helping his students learn. This quarter of MENU was definitely challenging
(like the other two), but there is a strong system of support from office hours and studying with MENU friends that makes the course
doable. 
- Apurva is very encouraging when you are struggling with a problem and you can really tell that he was excited about math and
teaching!        
- He is really passionate about the subject and explains things well. He is very funny and approachable in class, and he gives a lot of
opportunities for students to ``check their understanding" by participating in class, working through problems as a class, etc. He
also would always stay after class for questions if anyone had any.