# Teaching Experience 

**This website is under construction and should be up-to-date by the end of September.**

Below is a list of courses I've taught in the past. 
<!-- FIXME: fix the above sentence -->

|                                             |                                                                     |
| ------------------------------------------- | ------------------------------------------------------------------- |
| 2023 Spring^[Northwestern University]       | Elementary Differential Equations                                   |
| 2023 Winter                                 | Foundations of Mathematics                                          |
| 2022-23                                     | MENU Linear Algebra and Multivariable Calculus (Course Coordinator) |
| 2021-22                                     | MENU Linear Algebra and Multivariable Calculus (Coordinated)        |
| 2022 Spring                                 | Introduction to Optimization                                        |
| 2022 Winter                                 | Introduction to Optimization                                        |
| 2021 Fall                                   | Single Variable Calculus (Coordinated)                              |
|                                             |                                                                     |
| 2021 Winter^[University of Western Ontario] | Algebraic Topology                                                  |
| 2021 Fall                                   | Discrete Structures for Engineering                                 |
| 2019 Winter                                 | Calculus II for Mathematical and Physical Sciences (Coordinated)    |
| 2019 Fall                                   | Calculus I for Mathematical and Physical Sciences (Coordinated)     |
| 2029 Fall                                   | Topics in Category Theory                                           |
|                                             |                                                                     |
| 2018 Fall^[Johns Hopkins University]        | Honors Single Variable Calculus                                     |
| 2018 Winter                                 | Symmetries & Polynomials                                            |
| 2017 Fall                                   | Honors Single Variable Calculus                                     |
| 2017 Winter                                 | Hitchhiker's Guide to Algebraic Topology                            |
| 2017 Summer                                 | Differential Equations with Applications                            |
| 2015 Summer                                 | Differential Equations with Applications                            |
| 2014 Summer                                 | Online Linear Algebra                                               |
|                                             |                                                                     |
| 2017-20                                     | Various Canada/USA Mathcamp courses                                 |
| 2018                                        | Canada/USA Mathcamp Academic Coordinator                            |


## Introduction to Optimization 

*Northwestern University, Fall and Winter 2021*

I taught this quarter long course for two quarters in Winter and Spring 2021. The course was aimed at upper level undergraduates majoring in math and economics and covered the topics of linear programming, simplex method, duality theory, and KKT conditions along with applications. 

- **Class Notes:** 
  Most textbooks I encountered were either too theoretical or too applied and I did not find a good fit for this course which needed to cover both the aspects. As such, I wrote detailed notes for this course which can be found here: [apurvanakade.github.io/Introduction-to-Optimization](https://apurvanakade.github.io/Introduction-to-Optimization/). 

- **Excel Worksheets:**
  I designed the course to have both a theoretical and a practical component. The lectures focused on the theory of optimization and the discussion sections on applications. Students had to model and solve optimization problems during the weekly discussion sections using the [Solver tool in Excel](https://support.microsoft.com/en-us/office/load-the-solver-add-in-in-excel-612926fc-d53b-46b4-872c-e24772f078ca). These were to be submitted at the end of the quarter and formed a significant assessment component.

## MENU Linear Algebra and Multivariable Calculus

This is an year long accelerated course covering the topics in linear algebra and
multivariable calculus. I was an instructor for this course in 2021-22 and am currently (2022-23) the course coordinator. 

- **Discussion worksheets:**
  My primary focus as a coordinator is to reduce student stress without comprimising with the accelerated nature of the course. For this, I reduced the amount of material covered in lectures and created meaningful discussion worksheets to complement the lecture materials. The discussion worksheets also enables me to incorporate an active learning component in the course. 


<!-- ## Foundations of Mathematics 

Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.

## Elementary Differential Equations 

Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum. -->

## Algebraic Topology 

In Winter 2021, I taught a semester-long course at UWO on Algebraic Topology aimed at graduate students and upper-level undergrads. The main textbook for the course was Hatcher but I rarely used the book at all. The course covers the fundamental group, covering spaces, and singular homology.

This was a fully online course aimed at upper-level undergraduates and graduate math students covering the basics of algebraic topology.  

[Problem Sets.](https://github.com/apurvnakade/uwo2021-algebraic-topology/tree/main/output)


## Discrete Structures for Engineering 

*Role:* Instructor - Fall 2021

This was a semester long four-credit course offered to second-year software engineering students. Students are introduced to fundamental concepts in discrete math, such as logic, combinatorics, modular arithmetic as well as proof-writing. I am the only instructor for this course, and
my class has nearly 200 students. I had to adapt the course to fit an online mode of delivery.

 Over the summer, I had to adapt a regular Discrete Math course to an online asynchronous setting. While I was preparing for the course, my priority was to reduce student anxiety, simplify the course delivery as much as possible, and minimize the screen time for students.

- Textbook:

  I decided to abandon the traditional textbooks and chose an online one, called \href{https://learn.zybooks.com/zybook/UWOMath2151ANakadeFall2020}{Zybooks}, which had interactive components and provided students with immediate feedback. The book is also extremely comprehensive and contains copious amounts of auto-graded exercises, in addition to several practice problems, which I assign weekly to help keep students on track. Finally, the book is exceptionally configurable, both in terms of content and structure.
  The textbook can be found here: \href{https://learn.zybooks.com/zybook/UWOMath2151ANakadeFall2020}{learn.zybooks.com/zybook/UWOMath2151ANakadeFall2020}


- Lectures:

  To minimize the amount of required screen-time for students, I made short videos for each topic instead of a long one for each lecture. Having a textbook that I knew would fill in the gaps left out by the short lectures was crucial for making this choice. I embed these video lectures directly within the textbook to provide a centralized resource to students, much like other online platforms such as Coursera and Kaggle.
  The video lectures are also available on YouTube at the following link: \href{https://www.youtube.com/playlist?list=PLXAOfwfSuiKm3cL-JftD9ndrjYi7fPcqN}{www.youtube.com/playlist?list=PLXAOfwfSuiKm3cL-JftD9ndrjYi7fPcqN}

- Exam:

  I decided to use \href{https://webwork.maa.org/}{WeBWork} to make exam problems.
  For this, I researched a lot about online testing platforms. I chose WeBWork because it is robust and reliable, and it allows for both internal randomization within a question and randomization between questions. Having an extensive repository of questions enables me to create unique exams for every student.

- Rubric for proofs:

  This course also introduced students to proof-writing.
  This was especially challenging to teach in an online asynchronous setting as it is not possible to provide students with immediate feedback.
  To remedy this, I decided to grade students on only the \emph{writing} part of proofs.
  I designed the homework questions based on the textbook questions (for which detailed solutions were provided) and provided students with a rubric on which their writing was going to be graded.
  The rubric can be found in Appendix \ref{sec:sample-teaching-materials}.

- WeBWorK questions repository:

  With my postdoc advisor and two students' help, we designed a repository of several hundred problems for discrete math on WeBWork.
  This repository is easily portable and can be adapted to any discrete math course.
  Furthermore, because WeBWorK is open-source this repository can be used by anyone freely.


- Discussion forums:

  I realized early on that communication was going to be the key to this course's smooth running. For this reason, I choose Piazza as a discussion forum to answer student questions and encourage them to answer each other’s problems. Piazza is very intuitive, easily searchable, and allows for anonymous posts.
  A demo of the discussion forum can be found here: https://piazza.com/demo_login?nid=kd1rr8nxc6z4b5&auth=f76e59e

- Centralized access:

  With students getting overwhelmed with the onslaught of online tools, it was necessary to make easily accessible. For this, with a little bit of tweaking, I embedded all the above websites into the school's LMS.


## Honors Single Variable Calculus  

At JHU, I got an opportunity to develop and teach Honors Single Variable Calculus for two semesters. This is an
experimental full semester four-credit course offered at JHU to first-year undergraduates. The course covers
all of the first-year calculus and introduces students to proof writing.

This is the first course I had to design from scratch. In the years before mine, the course was mostly taught
in a lecture format. I decided to transition to a fully inquiry-based format. For this, I took the suggested
textbook for this course and converted it into weekly guided exercises. Because the classes were small, I
often dynamically modified the course material to suit the class. Designing this course gave a profound
insight into the process of student learning and helped me combat expert blind spots. The materials for this
course can be found here: https://apurvanakade.github.io/for-students.html#honors-single-variable-calculus

## Intersession Courses 

I taught two week-long intersession courses titled Hitchhiker's Guide to Algebraic Topology and Symmetries
& Polynomials. I taught both of these courses in a flipped classroom format. I assigned students guided
exercises, which they solved to learn more about the subject. What was both challenging and fun was that
the students were not math majors, and so I had to remove all the mathematical jargon and could not even
expect them to know how to write proofs. As such, I had to design my course around concrete examples and
find easily accessible concepts.

For Hitchhiker's Guide to Algebraic Topology, I asked the students to read and present applications of algebraic
topology to other fields of science of their choosing. We had several exciting conversations about things like
applications of knot theory to protein folding and data science. The notes and the student presentations can
be found here: apurvanakade.github.io/courses/2017 h2g2 alg top/index.html

This 2-week class from the Intersession 2017 at JHU introduces non-math majors to algebraic topology and its applications. There are no prerequisites.



In the Symmetries & Polynomials course, I taught students group theory using permutations of elements
and its connection to Galois theory using roots of polynomials. During class, I would divide students into

This 2-week class from Intersession 2018 at JHU non-math majors to group theory and its connections to roots of polynomials, in particular, the unsolvability of the quintic. The class is designed in an IBL-format - you're expected to solve all the problems in each section before moving to the next and in the process learn the subject. The prerequisites are basic proof techniques.


## Canada/USA Mathcamp 

I taught at an intensive, residential, five-week summer camp for mathematically talented high school
kids for five summers. The academic day at the camp is filled with classes, talks, and office hours with
more than 100 courses offered each summer, covering material typically only encountered in college or
grad school. My non-teaching duties included living in the dorms with students as an RA, being an
academic advisor, and advising students on which courses to take. More information can be found here:
https://www.mathcamp.org/jobs/grad_students/

- Mentor: 

  I designed and taught week-long courses on advanced mathematical topics such as linear
  algebra, manifolds, Riemann surfaces, representation theory, computer-assisted theorem proving, and
  mentored several reading and coding projects. A defining feature of Mathcamp is that each student
  designs their own schedule (with the guidance of an academic advisor). As such, the courses need to
  be designed to be both interesting and challenging.
  This year I had the added challenge of doing this online. For this, I decided to create a hybrid
  coding/math course that introduced students to computer-assisted theorem proving. For my more
  traditional courses, I taught using Jamboard, which allowed students to scroll through the previous
  pages. Notes from my Mathcamp classes can be found here: https://apurvanakade.github.io/
  teaching.html#canadausa-mathcamp.

  - Lean at MC2020
  - Crash course on linear algebra
  - Galois correspondence of covering spaces
  - From high school arithmetic to group cohomology
  - Cohomology via sheaves
  - How curved is a potato
  - Would I ever lie group to you?
  - Riemann surfaces
  - All things manifoldy


- Academic Coordinator: 

  In the summer of 2017, I was one of the two academic coordinators at Mathcamp. The academic coordinators are responsible for designing and running all the educational
  activities, including inviting and hosting external visitors, preparing a balanced five-week class schedule (more than 100 classes), assigning (110) students to projects, teaching, and being a part of the hiring
  team. More information can be found here: https://www.mathcamp.org/2018/staff/


## Formalization in LEAN
