# Grants \& Awards

## Open Educational Resources Faculty Grant, NU 2022

I and Aaron Greicius received a $10K Open Educational Resources Faculty Grant at Northwestern University.
The grant is for adding interactive WeBWorK, and SageMath exercises to Aaron's open-source Linear Algebra textbook available here: http://linear-algebra.northwestern.pub/frontmatter-1.html.
We hope to make the book self-contained and a complete replacement for a standard linear algebra text.
I have prior experience with WeBWorK which has helped us get started immediately.

## Undergraduate teaching awards

- **William Kelso Morrill Award for Excellence in Mathematics**, JHU 2019

This award is granted by the JHU Mathematics Department each year to the graduate student who best displays a love of teaching, love of mathematics, and concern for students.
[Website](https://sites.krieger.jhu.edu/math-intranet/for-graduate-students/graduate-awards/).


- **Finalist for the KSAS Excellence in Teaching Awards**, JHU 2019

The award honors the best graduate TAs in the Krieger School of Arts and Sciences, JHU for the care and concern they take with their subject and their students.
[Website](https://krieger.jhu.edu/teaching-award/).

- **Prof. Joel Dean award for Excellence in Teaching in Mathematics**, JHU 2016

Annual award to recognize graduate students and faculty who have exhibited extraordinary performance in teaching undergraduates

## AMS Graduate Student Travel Grant 2019

I was awarded a $250 travel grant by AMS for giving a talk at AMS Sectional Meeting
