# Mentoring 

## Causeway Postbaccalaureate Program
I am a supplemental instructor for the [Causeway Postbaccalaureate Program](https://sites.northwestern.edu/causeway/)
at Northwestern University for the 2022-23 academic year. 
My duties include meeting with the participants weekly as a tutor in addition to holding office hours and liaising with course instructors to provide additional examples, exercises, and review for the students. 

The Causeway Postbaccalaureate Program is a yearlong experience in mathematics that seeks to increase the number of graduate students in the mathematical sciences from historically underrepresented groups. Beginning in July 2021, Causeway participants will undertake a rigorous program of study in foundational coursework; work closely with Northwestern faculty on an appropriate research project; and receive career mentoring while serving as mentors for other groups themselves.

## Northwestern Emerging Scholar's Program 
I am a co-director of the [Northwestern Emerging Scholar's
Program](https://www.math.northwestern.edu/undergraduate/prizes-competitions-organizations/northwestern-emerging-scholars.html).
My duties include coordinating weekly math-circle sessions for first year undergrads and various administrative tasks such as preparing problem sheets and advertising etc.

## Directed Reading Program 
I've helped *start* and organize the [DRP at
UWO](https://www.math.uwo.ca/undergraduate/current_students/directed_reading_program.html) and in
the past have co-organized the [DRP at JHU](https://math.jhu.edu/drp.html). The Directed Reading
Program is a program in which undergrads are paired with a graduate student/postdoc whose interests
align with theirs and they study a topic of their choice for one semester. It is intended to help
motivated students explore topics in more depth than possible in a classroom setting. 

## Topics in Category Theory 

In Fall 2019, I supervised a topics course on topics in category theory for graduate students at UWO. 
We covered topics from Weibel's Homological Algebra and Emily Riehl's Category Theory in Context textbooks.