# Professional Development

## Project NExT
Mathematical American Association’s [Project NExT (New Experiences in Teaching)](https://www.maa.org/programs-and-communities/professional-development/project-next) is a professional development program for new or recent Ph Ds in the mathematical sciences. It addresses all aspects of an academic career:

- Improving the teaching and learning of mathematics
- Engaging in research and scholarship
- Finding exciting and interesting service opportunities
- Participating in professional activities

This program provided me the opportunity to connect with and learn from other math educators from all over the country.
Since participating in the program, I've joined various MAA communities and actively learned from others' experiences.

## JHU Teaching Academy Certification 
I have obtained a [teaching certification](https://ctei.jhu.edu/teaching-academy/coc) from the
[Teaching Academy at JHU](https://ctei.jhu.edu/teaching-academy). 
The Teaching Academy’s Certificate of Completion program is designed to help prepare Ph.D. students and Post-doctoral Fellows for academic careers and assist in acquiring a foundation for the teaching responsibilities associated with their first faculty appointments. 
This program exposed me to teaching as a scholarship and got me started in my current career as a math educator.

## SIMIODE Workshop
I attended a week-long MAA Open Math workshop in Summer 2022 about teaching differential equations using a modeling first approach. 
This workshop was based on resources from [SIMIODE (Systemic Modelling Opportunities with Differential Equations)](https://qubeshub.org/community/groups/simiode). The workshop was highly relevant as I will be teaching this course in Winter 2023. I intend to redesign it to make it more applied and incorporate projects in assessments. I also plan to use the newly published [SIMIODE textbook](https://qubeshub.org/community/groups/simiode/textbook) as the primary textbook.
The workshop was well-organized, and I learned a thing or two about how to run an excellent online program.

## SIGMAA IBL 
I have been attending [SIGMAA IBL](http://sigmaa.maa.org/ibl/) (Special Interest Group of the Mathematical Association of America for Inquiry-Based Learning) workshops since joining Project NExT. 
IBL SIGMAA aims to bring practitioners and others interested in IBL together to share teaching resources and experiences, encourage and publicize research related to IBL, and promote the proliferation of IBL in Mathematics through conversation and professional development. 
I regularly attend their monthly talks about IBL teaching resources and experiences.
This quarter I've started regularly attending the [Online Seminar in Undergraduate Math Education](https://olsume.org/) covering similar topics.

## Critical Issues in Math Education Workshop
I attended the [CIME workshop](https://www.msri.org/workshops/1028) at MSRI in Summer 2022. 
The workshop brought together teachers and researchers from universities, community colleges, and K-12 schools. The goal was to explore the reasons for and processes by which change in university mathematics departments is initiated, promoted and sustained and lessons learned from change efforts in K-12. 

## Northwestern Excellence in Teaching Alliance
From 2021-22, I participated in Northwestern's teaching alliance program. 
The program provided reading resources and guides through a Canvas course hosted by the Searle teaching center at Northwestern.
We met in small cohorts monthly to engage in conversations led by a faculty peer around teaching and learning. 

## Mastery Grading
In Summer 2019, I participated in a workshop on mastery grading. 
During the workshop, we learned about standards-based grading, and we heard about how it has been implemented across a variety of courses. 
I am considering implementing this grading system in the Intro to Proofs course I'm teaching in Winter 2023.

## Science of Learning Symposium, JHU 
I attended a biennial Science of Learning symposium at JHU from 2014-18. 
The event brought together experts in cognitive science, neuroscience, education, and other fields to explore different perspectives on the cognitive and neural bases for learning and motivation.
I found the insights about the physiological basis of learning to be very helpful.
I have since read more about these topics and completed the "Learning how to learn" course on Coursera.