---
title: "Teaching Portfolio"
author: "Apurva Nakade"
date: "`r Sys.Date()`"
output: pdf_document
documentclass: report
github-repo: apurvanakade/Teaching-Portfolio
url: https\://github.com/apurvanakade/Teaching-Portfolio
description: Teaching Portfolio.
site: bookdown::bookdown_site
---

# Introduction {.unnumbered}

I am a postdoctoral lecturer in the Department of Mathematics at Northwestern
University. I was a postdoctoral fellow at the University of Western
Ontario from 2019 to 2021. I obtained my Ph.D. from JHU in 2019 with a thesis titled _An application of
the h-principle to Manifold Calculus_.

My academic responsibilities have included:

- coordinating and teaching multi-section courses,
- teaching in-person and online courses with several hundred students,
- adapting large service courses for asynchronous education,
- creating advanced electives and short boot camp courses for small groups of students,
- managing TAs,
- hiring mentors for summer camps,
- supervising reading courses and reading programs,
- creating open education resources such as video lectures and Webwork questions, 
- creating course content using RMarkdown and PreTeXt,
- formalizing mathematics in Lean theorem prover.

I have taught topics spanning calculus, linear algebra, differential equations, linear programming, discrete math, math formalization, manifolds, and algebraic topology.
In recent years, my focus has been on creating course content that is reusable, adaptable, and freely available. 
I'm interested in creating and redesigning interdisciplinary math courses focusing on real-world applications and modeling.

<!-- My current focus is on incorporating technology into my courses, creating course resources that can be used asynchronously by students thereby providing additional support to instructors outside of classroom, and making courses more useful to students interested in applied fields. -->


<!-- In recent years, my focus has been on creating course content that is reusable, adaptable, and freely available. 
I'm interested in creating and redesigning interdisciplinary math courses focusing on real-world applications and modeling, incorporating the use of computational software such as SageMath and Excel.
I have also been experimenting with educational technologies for content delivery, student engagement, and student assessments.
A math classroom needs to evolve into a dynamic and hybrid space where students are able to meaningfully engage in ways that are relevant to them.
It is also possible (and essential) to achieve this in a way that does not put undue burden upon the instructors by providing them with help and resources. -->

<!-- My strengths lie in being good at organization and coaching students individually. 
What students need more than content delivery is a coach and a mentor who can point out their habitual mistakes and provide individual feedback. 
I establish structure and create resources to free up time to discuss math with students individually.
I make students work on problems in all of my classes.
I hold my office hours, which are always packed, in large collaborative spaces where students learn by helping each other. 
In the future, I see myself using these skills to help other instructors and TAs succeed in their teaching. -->